name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DUNE_PROFILE: release
  OCAMLRUNPARAM: b

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 5.3.0

    steps:
      - uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3.4.5
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          opam-disable-sandboxing: true

      - name: Install opam deps
        run: opam install . --deps-only --with-test -y

      - name: Build
        run: opam exec -- dune build

      - name: Check formatting
        run: opam exec -- dune build @fmt

      - name: Run tests
        run: opam exec -- dune runtest
